source_url: https://xkcd.com
db_file: database.json
index_file: index.json
# пробовал разные значения, это показалось оптимальным по времени
# скорость сильно зависит, от того какой раз подряд запускаешь программу
# вероятно на сайте https://xkcd.com/ есть кэш и при многочисленных запусках
# программа начинает работать сильно быстрее благодаря ему 
parallel: 25